# This workflow will run when code is pushed to the 'main' branch.
name: Deploy to AWS

on:
  push:
    branches:
      - main # Or 'master', depending on your repository's default branch

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install Dependencies
        working-directory: ./infrastructure # Run npm install in the correct directory
        run: npm install

      - name: Run Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: diversitus/diversitus_development # Your Pulumi stack name
          work-dir: ./infrastructure # The directory of your Pulumi project
        env:
          # Pass the secrets to the Pulumi action
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" # Set the AWS region explicitly